---
abstract: 'Write Perl bindings to non-Perl libraries with FFI. No XS required.'
author:
  - 'Graham Ollis <plicease@cpan.org>'
build_requires:
  Alien::FFI: '0.012'
  Module::Build: '0.3601'
  Test::More: '0.94'
  perl: '5.008001'
configure_requires:
  Alien::FFI: '0.12'
  Config::AutoConf: '0.309'
  ExtUtils::CBuilder: '0'
  FFI::CheckLib: '0.05'
  Module::Build: '0.3601'
  perl: '5.008001'
dynamic_config: '1'
generated_by: 'Dist::Zilla version 6.003, CPAN::Meta::Converter version 2.150005'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: FFI-Platypus
no_index:
  directory:
    - examples
requires:
  ExtUtils::CBuilder: '0'
  FFI::CheckLib: '0'
  File::ShareDir: '0'
  JSON::PP: '0'
  Module::Build: '0.3601'
  constant: '1.32'
  perl: '5.008001'
resources:
  IRC: irc://irc.perl.org/#native
  bugtracker: https://github.com/plicease/FFI-Platypus/issues
  homepage: http://perl.wdlabs.com/FFI-Platypus
  repository: git://github.com/plicease/FFI-Platypus.git
version: '0.42'
